version: "3.8"

services:
  wordpress:
    env_file:
      - ./.env
    image: ghcr.io/hansanghyeon/wordpress-redis:5.8.2-php8.0-apache-redis
    networks:
      - traefik_proxy
      - default
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: wp
      WORDPRESS_CONFIG_EXTRA: |
        /* Redis */
        define('WP_REDIS_HOST', getenv_docker('WORDPRESS_REDIS_HOST', 'redis'));
        define('WP_REDIS_PORT', getenv_docker('WORDPRESS_REDIS_PORT', 6379));
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./src:/var/www/html/wp-content/themes/sage
    labels:
      - traefik.enable=true
      - traefik.http.routers.work-202110__${PROJECT_NAME}.entrypoints=websecure
      - traefik.http.routers.work-202110__${PROJECT_NAME}.rule=Host(`${PROJECT_NAME}.demo.beeclover.pro`)
      - traefik.http.routers.work-202110__${PROJECT_NAME}.tls.certresolver=leresolver
      - traefik.http.routers.work-202110__${PROJECT_NAME}.service=work-202110__${PROJECT_NAME}
      - traefik.http.services.work-202110__${PROJECT_NAME}.loadbalancer.server.port=80

      - traefik.http.routers.work-202110__${PROJECT_NAME}_admin.entrypoints=websecure
      - traefik.http.routers.work-202110__${PROJECT_NAME}_admin.rule=Host(`${PROJECT_NAME}.demo.beeclover.pro`) && PathPrefix(`/wp-content/uploads/{year:[0-9]+}/{month:[0-9]+}/`)
      - traefik.http.routers.work-202110__${PROJECT_NAME}_admin.tls.certresolver=leresolver
      - traefik.http.routers.work-202110__${PROJECT_NAME}_admin.service=work-202110__${PROJECT_NAME}_admin
      - traefik.http.services.work-202110__${PROJECT_NAME}_admin.loadbalancer.server.port=80
      - traefik.http.routers.work-202110__${PROJECT_NAME}_admin.middlewares=favicon@file, wordpress_admin_check@file
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: wp
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - ./.db:/var/lib/mysql

  redis:
    image: redis:latest
    volumes:
      - redis:/data

########################### NETWORKS
networks:
  traefik_proxy:
    external: true
volumes:
  redis: null
